---
title: "Arthropods on Iva: partitioning of variation"
output: md_notebook
---


### Preparation

##### cleanup workspace

```{r}
rm(list = ls()) # clean work space
                # use ``Ctrl + L` to clean console 
```

##### load libraries

```{r, echo = FALSE}
#   install.packages("vegan")
library("vegan")
```

##### load data

```{r}
source("loadData.R")
```

(check data)

```{r}
head(Xs_PL,2)
```

## Partitioning of variation using `varpart`

```{r}
mod_tPL <- varpart(Yt_PL, ~ ., Xs_PL$Latitude, Xs_PL$Month , data = Xe_PL, transfo="log")
                         # ^^^ using all data in `Xe_PL`     
mod_gPL <- varpart(Yg_PL, ~ ., Xs_PL$Latitude, Xs_PL$Month , data=Xe_PL, transfo="log")
mod_tST <- varpart(Yt_ST, ~ ., Xs_ST$Latitude, Xs_ST$Month , data=Xe_ST, transfo="log")
mod_gST <- varpart(Yg_ST, ~ ., Xs_ST$Latitude, Xs_ST$Month , data=Xe_ST, transfo="log")
```




### plots
```{r}
mod_gST
```

Result at plant (the smaller) scale:
```{r}
par(mfrow = c (1,2))
p1 <- plot(mod_tPL, 
           bg = c("hotpink","skyblue", "burlywood"),
           Xnames=c('Plant', 'Latitude','Month'))
      title(main= 'Taxon-based, plant scale' )
p2 <- plot(mod_gPL, 
           bg = c("hotpink","skyblue", "burlywood"),
           Xnames=c('Plant', 'Latitude','Month'))
      title(main= 'Guild-based, plant scale' )
```

```{r}
par(mfrow = c (1,2))
p3 <- plot(mod_tST, 
           bg = c("hotpink","skyblue", "burlywood"),
           Xnames=c('Plant','Latitude','Month'))
      title(main= 'Taxon-based, site scale' )
p4 <- plot(mod_gST, 
           bg = c("hotpink","skyblue", "burlywood"),
           Xnames=c('Plant', 'Latitude','Month'))
      title(main= 'Guild-based, site scale' )
```

### another way of plotting
```{r}
library(devtools)
install_github("weitingwlin/vennchart")

library(vennchart)
```



```{r}
valueParse <-function(mod)  {
   a <-   mod$part$indfract$Adj.R.square
  
  #  showvarparts(3)
  
  A <- a[1] + a[4] + a[6] + a[7] # a + d + f + g
  B <- a[2] + a[4] + a[5] + a[7] # b + d + e + g
  C <- a[3] + a[5] + a[6] + a[7] # c + e + f + g
  AB <- a[4] + a[7] # d + g
  AC <- a[6] + a[7] # f + g
  BC <- a[5] + a[7] # e + g
  ABC <- a[7]
  res <- a[8]
  
  out <- list("A" = A, "B" = B, "C" = C,
              "AB" = AB, "AC" = AC, "BC"= BC,
              "pureA"= a[1],"pureB"= a[2],"pureC"= a[3],
              "res" = res)
  
  return(out)
}
```

# site scale

```{r,fig.width = 12, fig.height = 6}
par(mfrow = c (1,2))
X <- valueParse(mod_tST)
L <- list("xlim" = c(-5,5), "ylim" = c(-6, 4))
Q1 <-  vennChart(A_all = X$A * 100, B_all = X$B * 100, C_all = X$C * 100,
                AandB = X$AB * 100, AandC = X$AC * 100, BandC = X$BC * 100, 
                names = c('Env.','Lat.', 'Mon.'),
                textadj = c(1.3,0), cex = 1.2, lim = L,
                unit = "%", digits = 2, texts = FALSE)

# print the text
Q1$textspos$tpBC[2] <- Q1$textspos$tpBC[2] + 1
Q1$textspos$tpAB[2] <- Q1$textspos$tpAB[2] - 1
Q1$textspos$tpAC[2] <- Q1$textspos$tpAC[2] - 1
plotVennTexts(Q1$textspos, names = c('Env.','Lat.', 'Mon.'), digits = 2,
                 cex = 1.2, unit = "%")

text(0, -5.8, 
     paste("Residual: ", as.character(round(X$res * 100, 2)) , "%"), 
     cex = 1.2)

title("Taxon-based \n Site scale")


X <- valueParse(mod_gST)
X[X<0]<-0
Q2 <-  vennChart(A_all = X$A * 100, B_all = X$B * 100, C_all = X$C * 100,
                AandB = X$AB * 100, AandC = X$AC * 100, BandC = X$BC * 100, 
                names = c('Env.','Lat.', 'Mon.'),
                textadj = c(1.3,0.2), cex = 1.2, lim = L,
                unit = "%", digits = 2, texts = FALSE)

Q2$textspos$tpA[1] <- Q2$textspos$tpA[1] + 2.6
Q2$textspos$tpA[2] <- Q2$textspos$tpA[2] + 4.8
Q2$textspos$tpB[1] <- Q2$textspos$tpB[1] + 4
Q2$textspos$tpB[2] <- Q2$textspos$tpB[2] - 2
plotVennTexts(Q2$textspos, names = c('Env.','Lat.', 'Mon.'), digits = 2,
                 cex = 1.2, unit = "%")

text(0, -5.8, 
     paste("Residual: ", as.character(round(X$res * 100, 2)) , "%"), 
     cex = 1.2)
title("Guild-based \n Site scale")
```

# plant scale

```{r,fig.width = 12, fig.height = 6}
par(mfrow = c (1,2))
X <- valueParse(mod_tPL)
Q3 <-  vennChart(A_all = X$A * 100, B_all = X$B * 100, C_all = X$C * 100,
                AandB = X$AB * 100, AandC = X$AC * 100, BandC = X$BC * 100, 
                 digits = 2, textadj = c(1.8, 0.4), lim = L,texts = FALSE)
Q3$textspos$tpBC[2] <- Q3$textspos$tpBC[2] - 1
Q3$textspos$tpAB[1] <- Q3$textspos$tpAB[1] + 0.6
Q3$textspos$tpAB[2] <- Q3$textspos$tpAB[2] + 0.6
plotVennTexts(Q3$textspos, names = c('Env.','Lat.', 'Mon.'), digits = 2,
                 cex = 1.2, unit = "%")
text(0, -5.8, 
     paste("Residual: ", as.character(round(X$res * 100, 2)) , "%"), 
     cex = 1.2)
title("Taxon-based \n Plant scale")
X <- valueParse(mod_gPL)
X[X<0]<-0
Q4 <-  vennChart(A_all = X$A * 100, B_all = X$B * 100, C_all = X$C * 100,
                AandB = X$AB * 100, AandC = X$AC * 100, BandC = X$BC * 100, 
                 lim = L,textadj = c(1.7,0.5), texts = FALSE)
# print the texts separately for more control

Q4$textspos$tpBC[2] <- Q4$textspos$tpBC[2] - 1
plotVennTexts(Q4$textspos, names = c('Env.','Lat.', 'Mon.'), digits = 2,
                 cex = 1.2, unit = "%")
text(0, -5.8, 
     paste("Residual: ", as.character(round(X$res * 100, 2)) , "%"), 
     cex = 1.2)
title("Guild-based \n Plant scale")
```









